hostname leaf_1
password zebra
log file /var/log/frr/bgpd.log

router bgp 64517
 timers bgp 3 9
 bgp router-id 10.255.0.5
 no bgp ebgp-requires-policy
 bgp bestpath as-path multipath-relax
 
 neighbor TOR peer-group
 neighbor TOR remote-as external
 neighbor TOR advertisement-interval 0
 neighbor TOR timers connect 10
 neighbor eth1 interface peer-group TOR
 neighbor eth2 interface peer-group TOR

 address-family ipv4 unicast
  neighbor TOR activate
  network 2.0.0.128/26
  network 2.0.0.192/27
  network 2.0.0.224/27
  redistribute connected route-map LOOPBACKS
  maximum-paths 64
 exit-address-family

 address-family l2vpn evpn
  neighbor TOR activate
  advertise-all-vni
 exit-address-family

route-map LOOPBACKS permit 10
 match interface lo
