#AS1

attacker[0]=A
attacker[image]="kathara/base"

r1[0]=A
r1[1]=B
r1[2]=C
r1[image]="kathara/frr"

r2[0]=U
r2[1]=B
r2[2]=E
r2[image]="kathara/frr"


r3[0]=AB
r3[1]=D
r3[2]=C
r3[image]="kathara/frr"

r4[0]=F
r4[1]=D
r4[2]=E
r4[image]="kathara/frr"

local[0]=AB
local[image]="kathara/bind"

#AS2

r5[0]=F
r5[1]=H
r5[2]=I
r5[3]=G
r5[4]=AC
r5[image]="kathara/frr"

tof_1[0]=J
tof_1[1]=H
tof_1[2]=K
tof_1[ipv6]=True
tof_1[image]="kathara/frr"

tof_2[0]=M
tof_2[1]=L
tof_2[2]=I
tof_2[ipv6]=True
tof_2[image]="kathara/frr"

spike_1[0]=J
spike_1[1]=L
spike_1[2]=O
spike_1[3]=N
spike_1[ipv6]=True
spike_1[image]="kathara/frr"

spike_2[0]=M
spike_2[1]=K
spike_2[2]=P
spike_2[3]=Q
spike_2[ipv6]=True
spike_2[image]="kathara/frr"

leaf_1[0]=R
leaf_1[1]=N
leaf_1[2]=P
leaf_1[ipv6]=True
leaf_1[image]="kathara/frr"

leaf_2[0]=S
leaf_2[1]=T
leaf_2[2]=O
leaf_2[3]=Q
leaf_2[ipv6]=True
leaf_2[image]="kathara/frr"

sniffer[0]=R
sniffer[1]=S
sniffer[image]="kathara/base"
sniffer[volume]="./catture|/catture|rw"

web_server[0]=R
web_server[image]="kathara-webserver-custom"
web_server[volume]="./storage/web|/var/www/html|rw"


spark[0]=S
spark[image]="kathara-spark-custom"
spark[volume]="./storage/src|/opt/spark/src|rw"
spark[volume]="./storage/data|/opt/spark/data|rw"

mongo_db[0]=S
mongo_db[image]="kathara-mongo-custom"
mongo_db[volume]="./storage/data|/data/db|rw"

llm[0]=T
llm[image]="kathara-llm-custom"
llm[volume]="./storage/models|/root/.ollama/models|rw"
llm[env]="NVIDIA_VISIBLE_DEVICES=all"
llm[env]="NVIDIA_DRIVER_CAPABILITIES=all"
llm[env]="OLLAMA_KEEP_ALIVE=-1"
llm[port]="11434:11434"
llm[bridged]=true


admin[0]=G
admin[image]="kathara-admin-custom" 
admin[volume]="./storage/src|/app|ro"
admin[volume]="./storage/data|/opt/spark/data|rw"
admin[volume]="./catture|/catture|ro"
admin[port]="8080:80"
admin[bridged]=true

local_a[0]=AC
local_a[image]="kathara/bind"

#AS3

r6[0]=U
r6[1]=V
r6[2]=Y
r6[image]="kathara/frr"

r7[0]=W
r7[1]=V
r7[image]="kathara/frr"

r8[0]=W
r8[1]=X
r8[image]="kathara/frr"

r9[0]=Y
r9[1]=Z
r9[image]="kathara/frr"

r10[0]=AA
r10[1]=Z
r10[image]="kathara/frr"

nsroot[0]=X
nsroot[image]="kathara/bind"

nsnet[0]=AA
nsnet[image]="kathara/bind"

tof_1[sysctl]="net.ipv4.fib_multipath_hash_policy=1"
tof_2[sysctl]="net.ipv4.fib_multipath_hash_policy=1"
spike_1[sysctl]="net.ipv4.fib_multipath_hash_policy=1"
spike_2[sysctl]="net.ipv4.fib_multipath_hash_policy=1"
leaf_1[sysctl]="net.ipv4.fib_multipath_hash_policy=1"
leaf_2[sysctl]="net.ipv4.fib_multipath_hash_policy=1"