hostname tof_2
password zebra
log file /var/log/frr/bgpd.log

ip prefix-list VERSO-AS1 permit 2.0.0.128/25 le 32
ip prefix-list VERSO-AS1 permit 10.0.0.0/8 le 32

router bgp 64514
    timers bgp 3 9
    bgp router-id 10.255.0.2
    no bgp ebgp-requires-policy
    bgp bestpath as-path multipath-relax
    
    neighbor fabric peer-group
    neighbor fabric remote-as external
    neighbor fabric advertisement-interval 0
    neighbor fabric timers connect 10
    neighbor eth0 interface peer-group fabric
    neighbor eth1 interface peer-group fabric

    neighbor 100.0.0.21 remote-as 2
    neighbor 100.0.0.21 description Router r5

    address-family ipv4 unicast
    neighbor fabric activate
    neighbor 100.0.0.21 prefix-list VERSO-AS1 out
    neighbor 100.0.0.21 activate
    redistribute connected route-map LOOPBACKS
    maximum-paths 64
    exit-address-family

    address-family l2vpn evpn
    neighbor fabric activate
    exit-address-family

    route-map LOOPBACKS permit 10
    match interface lo
