hostname r5
password zebra
log file /var/log/frr/bgpd.log

! Rotte che r5 accetta da r4 (AS1) e che annuncia a tof_1 (verso DC)
ip prefix-list DA-AS1 permit 192.168.20.0/23 le 32
ip prefix-list DA-AS1 permit 2.0.0.0/25 le 32
ip prefix-list DA-AS1 permit 10.0.0.0/8 le 32

! Rotte che r5 annuncia verso r4 (AS1): le reti del DC e di admin/local_a
ip prefix-list VERSO-AS1 permit 2.0.0.128/25 le 32
ip prefix-list VERSO-AS1 permit 10.0.0.0/8 le 32

! Blocca tutto (usata per policy monodirezionale)
ip prefix-list DIVIETO deny 0.0.0.0/0 le 32


router bgp 2

    no bgp network import-check

    neighbor 1.0.0.1 remote-as 1
    neighbor 1.0.0.1 description Router r4

    neighbor 100.0.0.18 remote-as 64514
    neighbor 100.0.0.18 description Router tof_1

    neighbor 100.0.0.22 remote-as 64514
    neighbor 100.0.0.22 description Router tof_2


    address-family ipv4 unicast
        ! AS1 <-> r5
        neighbor 1.0.0.1 prefix-list VERSO-AS1 out
        neighbor 1.0.0.1 prefix-list DA-AS1 in
        neighbor 1.0.0.1 activate

        ! r5 -> tof_1: manda le rotte AS1 + admin/local_a nel fabric (percorso di ingresso)
        neighbor 100.0.0.18 prefix-list DA-AS1 out
        neighbor 100.0.0.18 prefix-list DIVIETO in
        neighbor 100.0.0.18 activate

        ! tof_2 -> r5: riceve le rotte DC (percorso di uscita)
        neighbor 100.0.0.22 prefix-list VERSO-AS1 in
        neighbor 100.0.0.22 prefix-list DIVIETO out
        neighbor 100.0.0.22 activate

        network 2.0.0.128/25
        network 10.0.0.0/8
    exit-address-family