hostname r5
password zebra
log file /var/log/frr/bgpd.log

ip prefix-list DA-AS1 permit 192.168.20.0/23 le 32
ip prefix-list DA-AS1 permit 2.0.0.0/25 le 32

ip prefix-list VERSO-AS1 permit 2.0.0.128/25 le 32
ip prefix-list VERSO-AS1 permit 10.0.0.0/8 le 32

ip prefix-list DIVIETO deny 0.0.0.0/0 le 32


router bgp 2

    no bgp network import-check
    
    neighbor 1.0.0.1 remote-as 1
    neighbor 1.0.0.1 description Router r4

    neighbor 100.0.0.18 remote-as 64514
    neighbor 100.0.0.18 description Router tof_1

    neighbor 100.0.0.22 remote-as 64514
    neighbor 100.0.0.22 description Router tof_2


    address-family ipv4 unicast
        neighbor 1.0.0.1 prefix-list VERSO-AS1 out
        neighbor 1.0.0.1 prefix-list DA-AS1 in
        neighbor 1.0.0.1 activate

        neighbor 100.0.0.18 prefix-list DA-AS1 out
        neighbor 100.0.0.18 activate

        neighbor 100.0.0.18 prefix-list DIVIETO in
        neighbor 100.0.0.18 activate

        neighbor 100.0.0.22 prefix-list VERSO-AS1 in
        neighbor 100.0.0.22 activate

        neighbor 100.0.0.22 prefix-list DIVIETO out
        neighbor 100.0.0.22 activate

        network 2.0.0.128/25
        network 10.0.0.0/8
    exit-address-family