hostname r2
password zebra
log file /var/log/frr/bgpd.log

ip prefix-list LAN-INTERNE permit 192.168.20.0/23
ip prefix-list LAN-INTERNE permit 10.0.0.0/8
ip prefix-list DA-AS3 permit 2.0.0.0/25

router bgp 1
    no bgp network import-check
    neighbor 1.0.0.6 remote-as 3
    neighbor 1.0.0.6 description Router r6

    address-family ipv4 unicast
        neighbor 1.0.0.6 prefix-list LAN-INTERNE out
        neighbor 1.0.0.6 prefix-list DA-AS3 in
        neighbor 1.0.0.6 activate
        network 192.168.20.0/23
        network 10.0.0.0/8
    exit-address-family