hostname r2
password zebra
log file /var/log/frr/ospfd.log

ip prefix-list DA-AS3 permit 2.0.0.0/26
ip prefix-list DA-AS3 permit 2.0.0.64/26

route-map BGP-TO-OSPF permit 10
    match ip address prefix-list DA-AS3

router ospf
    network 100.0.0.0/28 area 0.0.0.0
    redistribute bgp route-map BGP-TO-OSPF
