hostname r2
password zebra
log file /var/log/frr/ospfd.log

ip prefix-list DA-AS3 permit 2.0.0.0/25

interface eth1
 ip ospf cost 100
!

router ospf
    network 100.0.0.0/28 area 0.0.0.0
    redistribute bgp
    distribute-list prefix DA-AS3 out bgp
