# ------------------------------------------------------------------------------
# AS 1: RETE ISP / ATTACCANTE (OSPF Area 1)
# ------------------------------------------------------------------------------
attacker[0]="net_att_r1"
attacker[image]="kathara/kali"

r1[0]="net_att_r1"
r1[1]="net_r1_r2"
r1[2]="net_r1_r3"
r1[image]="kathara/frr"

# R2: ABR (Area Border Router) - Collega Area 1 e Area 0
r2[0]="net_r1_r2"
r2[1]="net_r2_r4"
r2[2]="net_r2_r8" # Dorsale verso AS3 (Area 0)
r2[image]="kathara/frr"

r3[0]="net_r1_r3"
r3[1]="net_r3_r4"
r3[image]="kathara/frr"

# R4: ASBR - Peering eBGP verso AS2
r4[0]="net_r2_r4"
r4[1]="net_r3_r4"
r4[2]="net_as1_as2" 
r4[image]="kathara/frr"

# ------------------------------------------------------------------------------
# AS 3: INFRASTRUTTURA DNS ROOT (OSPF Area 0 - Backbone)
# ------------------------------------------------------------------------------
r8[0]="net_r2_r8"
r8[1]="net_r8_r9"
r8[image]="kathara/frr"

r9[0]="net_r8_r9"
r9[1]="net_r9_r10"
r9[image]="kathara/frr"

r10_dns[0]="net_r9_r10"
r10_dns[image]="kathara/base"

# ------------------------------------------------------------------------------
# AS 2: DATA CENTER (Fat-Tree 3-Tier) & SOC LAN
# ------------------------------------------------------------------------------

# 0. BORDER ROUTER (Core Gateway di AS2)
# Gestisce le politiche BGP per forzare l'ingresso su ToF1 e l'uscita su ToF2
r5[0]="net_as1_as2" # Link BGP esterno
r5[1]="net_r5_tof1" # Primario ENTRATA (Inbound)
r5[2]="net_r5_tof2" # Primario USCITA (Outbound)
r5[3]="net_soc_lan" # Corporate LAN dedicata
r5[image]="kathara/frr"

# 1. TOP OF FABRIC LAYER (ToF / Core)
tof1[0]="net_r5_tof1"
tof1[1]="link_tof1_sp1"
tof1[2]="link_tof1_sp2"
tof1[image]="kathara/frr"

tof2[0]="net_r5_tof2"
tof2[1]="link_tof2_sp1"
tof2[2]="link_tof2_sp2"
tof2[image]="kathara/frr"

# 2. SPINE LAYER (Aggregation)
spine1[0]="link_tof1_sp1"
spine1[1]="link_tof2_sp1"
spine1[2]="link_sp1_lf1"
spine1[3]="link_sp1_lf2"
spine1[image]="kathara/frr"

spine2[0]="link_tof1_sp2"
spine2[1]="link_tof2_sp2"
spine2[2]="link_sp2_lf1"
spine2[3]="link_sp2_lf2"
spine2[image]="kathara/frr"

# 3. LEAF LAYER (Access & Microsegmentazione)
leaf1[0]="link_sp1_lf1"
leaf1[1]="link_sp2_lf1"
leaf1[2]="net_dmz"
leaf1[image]="kathara/frr"

leaf2[0]="link_sp1_lf2"
leaf2[1]="link_sp2_lf2"
leaf2[2]="net_app"
leaf2[3]="net_db"
leaf2[image]="kathara/frr"

# ------------------------------------------------------------------------------
# ENDPOINTS & MANAGEMENT
# ------------------------------------------------------------------------------

# PC Amministratore fuori dal fabric (SOC LAN)
admin_pc[0]="net_soc_lan"
admin_pc[image]="python:3.10-slim"
admin_pc[port]="8501:8501"

# Servizi in DMZ (Sotto Leaf 1)
web_server[0]="net_dmz"
web_server[image]="kathara/base"

sniffer[0]="net_dmz" 
sniffer[image]="kathara/kali"

# Analisi e Database (Sotto Leaf 2)
spark[0]="net_app"
spark[image]="kathara/base"

mongodb[0]="net_db"
mongodb[image]="mongo:7.0"