hostname r6
password zebra
log file /var/log/frr/bgpd.log

ip prefix-list DA-AS1 permit 192.168.20.0/24
ip prefix-list DA-AS1 permit 192.168.21.0/24

ip prefix-list VERSO-AS1 permit 2.0.0.0/26
ip prefix-list VERSO-AS1 permit 2.0.0.64/26

router bgp 3

    no bgp network import-check
    
    neighbor 1.0.0.5 remote-as 1
    neighbor 1.0.0.5 description Router r2


    address-family ipv4 unicast
        neighbor 1.0.0.5 prefix-list VERSO-AS1 out
        neighbor 1.0.0.5 prefix-list DA-AS1 in
        neighbor 1.0.0.5 activate

        network 2.0.0.0/26
        network 2.0.0.64/26
    exit-address-family