hostname r6
password zebra
log file /var/log/frr/bgpd.log

ip prefix-list DA-AS1 permit 192.168.20.0/23
ip prefix-list VERSO-AS1 permit 2.0.0.0/25

router bgp 3
    no bgp network import-check
    neighbor 1.0.0.5 remote-as 1
    neighbor 1.0.0.5 description Router r2

    address-family ipv4 unicast
        neighbor 1.0.0.5 prefix-list VERSO-AS1 out
        neighbor 1.0.0.5 prefix-list DA-AS1 in
        neighbor 1.0.0.5 activate
        network 2.0.0.0/25
    exit-address-family