hostname r6
password zebra
log file /var/log/frr/ospfd.log


ip prefix-list DA-AS1 permit 192.168.20.0/23
ip prefix-list DA-AS1 permit 10.0.0.0/8

route-map BGP-TO-OSPF permit 10
    match ip address prefix-list DA-AS1

router ospf
    network 100.0.0.32/28 area 0.0.0.0
    redistribute bgp route-map BGP-TO-OSPF
