hostname r6
password zebra
log file /var/log/frr/ospfd.log

ip prefix-list DA-AS1 permit 192.168.20.0/24
ip prefix-list DA-AS1 permit 192.168.21.0/24

route-map BGP-TO-OSPF permit 10
    match ip address prefix-list DA-AS1

router ospf
    network 100.0.0.32/30 area 0.0.0.0
    network 100.0.0.40/30 area 1.1.1.1
    redistribute bgp route-map BGP-TO-OSPF
