hostname r4
password zebra
log file /var/log/frr/bgpd.log

ip prefix-list VERSO-AS2 permit 192.168.20.0/23
ip prefix-list VERSO-AS2 permit 2.0.0.0/25


ip prefix-list DA-AS2 permit 2.0.0.128/25


router bgp 1

    no bgp network import-check
    
    neighbor 1.0.0.2 remote-as 2
    neighbor 1.0.0.2 description Router r5


    address-family ipv4 unicast
        neighbor 1.0.0.6 prefix-list VERSO-AS2 out
        neighbor 1.0.0.6 prefix-list DA-AS2 in
        neighbor 1.0.0.6 activate

        network 192.168.20.0/25
        network 2.0.0.0/23
    exit-address-family