hostname r4
password zebra
log file /var/log/frr/ospfd.log

ip prefix-list DA-AS2 permit 2.0.0.128/25
ip prefix-list DA-AS2 permit 10.0.0.0/8

router ospf
    ospf router-id 4.4.4.4
    network 100.0.0.0/28 area 0.0.0.0
    redistribute bgp
    distribute-list prefix DA-AS2 out bgp
